---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
    release: {{ .Release.Name }}
    version: {{ .Values.deployment.image.version }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
      annotations:
        linkerd.io/inject: {{ .Values.serviceMesh.status }}
        config.linkerd.io/opaque-ports: "80"
    spec:
      imagePullSecrets:
      - name: {{ .Values.registry.secretName }} 
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.deployment.image.name }}:{{ .Values.deployment.image.version }}
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.deployment.port }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
            optional: false
        resources:
          limits:
            cpu: {{ .Values.deployment.limits.cpu }}
            memory: {{ .Values.deployment.limits.memory }}
          requests:
            cpu: {{ .Values.deployment.requests.cpu }}
            memory: {{ .Values.deployment.requests.memory }}
