# ID da aplicacao
app:
  # defina sempre o nome do app
  # deve ser um nome unico no namespace
  name: ms-rab
  # o grupo de apps ao qual este app pertence
  group: arlepton

# informacoes sobre o deployment
deployment:
  # quantidade de replicas do pod
  replicas: 1
  # porta exposta pelo container
  port: 8080
  # requests de cpu e memoria
  requests:
    cpu: 100m
    memory: 128Mi
  # limites de cpu e memoria
  limits:
    cpu: 200m
    memory: 256Mi
  # informacoes da imagem docker 
  image:
    # nome da imagem, incluindo o registry docker, diretorios e nome
    # por exemplo: nbc.azureacr.io/portal-correspondente/ms-email 
    # name: artifact.kalico.one/apis/ms-rab
    name: artifact.kalico.one/apis/ms-rab
    # versao da imagem docker
    version: 1.0.0
    # estrategia de pull policy
    pullPolicy: Always

# servico kubernetes
service:
  # tipo do service: ClusterIP / NodePort / LoadBalancer
  type: ClusterIP
  # Node Port - usado quando o serviço nao é ClusterIP
  nodePort: 32754

#Service Mesh
serviceMesh:
  # enabled / disabled
  status: enabled

# Configmap
configmap:
  # define se o configmap deve ser criado ou nao
  create: true
  # nome do configmap
  name: ms-rab-cm
  # dados do configmap
  # usado somente em caso de configmap.create = true
  data:
    dbUrl: jdbc:h2:./data/arlepton
    dbUsername: ms-rab
    dbPassword: ms-rab@123
    rabbitHost: localhost
    rabbitPort: 5672
    rabbitUsername: ms-rab
    rabbitPassword: ms-rab@123
    rabbitVirtualHost: /

# StorageClass para volumes
persistence:
  # true ou false
  enable: false
  # Nome do StorageClass responsavel pela criacao do Persistence Volume
  # usado em caso de persistence.enable = true
  storageClassName: default
  # path absoluto do diretorio de armazenamento dentro do container
  # usado em caso de persistence.enable = true
  mountPath: /app/data
  # Tamanho do Persistence Volume requerido
  # usado em caso de persistence.enable = true
  size: 4Gi

# Configuracoes para Secret de registry-pull
registry:
  # se deve criar a secret registry-pull ou nao
  createSecret: false
  # nome da secret para pull de imagens
  secretName: registry-pull
  # usado somente em caso de registry.createSecret = true
  # registry host (dns)
  host: artifact.kalico.one
  # usuario do registry docker
  user: arphoenix
  # senha do registry docker
  pwd: password-here
