arlepton:
  features:
    cache:
      enable: ${ARLEPTON_FEATURES_ENABLE_CACHE:false}
    cors:
      enable: ${ARLEPTON_FEATURES_ENABLE_CORS:true}
      allowedOrigins: ${ARLEPTON_FEATURES_ALLOWED_ORIGINS:http://localhost:3001, http://arlepton.com, http://localhost:8080}
    email:
      enable: ${ARLEPTON_FEATURES_EMAIL_ENABLE:false}
      protocol: ${ARLEPTON_FEATURES_EMAIL_PROTOCOL:smtp}
      host: ${ARLEPTON_FEATURES_MAIL_HOST:smtp.gmail.com}
      port: ${ARLEPTON_FEATURES_MAIL_PORT:587}
      username: ${ARLEPTON_FEATURES_MAIL_USERNAME:finhat2@gmail.com}
      password: ${ARLEPTON_FEATURES_MAIL_PASSWD:lmgxinxclovehtfp}
      debug: ${ARLEPTON_FEATURES_MAIL_DEBUG:true}
      recovery-password:
        domain: ${ARLEPTON_FEATURES_MAIL_RESET_DOMAIN:http://localhost:3001}
        token-ttl-minutes: ${ARLEPTON_FEATURES_MAIL_RESET_TOKEN:1}
      smtp:
        auth: true
        starttls:
          enable: true
          require: true
    security:
      enable: 
      # valores possíveis: oauth2, internal, none
      mode: none 

openapi:
  service:
    title: Msrab API
    version: 1.0.0

springdoc:
  swagger-ui:
    enabled: true
  show-actuator: false
  packagesToScan: br.com.arphoenix.apis.msrab.controller

server:
  compression:
    enabled: true
  port: 8080
  servlet: 
    context-path: /

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: ms-rab
  banner:
    location: classpath:bann.txt
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  messages:
    basename: i18n/messages
  datasource:
    platform: h2
    url: ${DB_URL:jdbc:h2:./data/arlepton}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:sa}
    continue-on-error: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:ms-rab}
    password: ${RABBIT_PASSWORD:ms-rab@123}
    virtual-host: ${RABBIT_VIRTUALHOST:/}
    connection-timeout: 9000

logging:
  level:
    root: INFO
    br.com.arphoenix.apis.msrab: INFO
    org.springframework.boot.context: INFO