{{- if .Values.configmap.create -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
    release: {{ .Release.Name }}
data:
  DB_URL: {{ .Values.configmap.data.dbUrl | quote }}
  DB_USERNAME: {{ .Values.configmap.data.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.configmap.data.dbPassword | quote }}
  RABBIT_HOST: {{ .Values.configmap.data.rabbitHost | quote }}
  RABBIT_PORT: {{ .Values.configmap.data.rabbitPort | quote }}
  RABBIT_USERNAME: {{ .Values.configmap.data.rabbitUsername | quote }}
  RABBIT_PASSWORD: {{ .Values.configmap.data.rabbitPassword | quote }}
  RABBIT_VIRTUALHOST: {{ .Values.configmap.data.rabbitVirtualHost | quote }}
{{- end -}}