---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
    release: {{ .Release.Name }}
    version: {{ .Values.deployment.image.version }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app.name }}
  ports:
  - name: frontend
    protocol: TCP
    port: 80
    targetPort: {{ .Values.deployment.port }}
    {{- if ne .Values.service.type "ClusterIP" -}}
    nodePort: {{ .Values.service.nodePort }}
    {{- end -}}